name: 'Validate Docs Metadata'

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install ajv and validate
        working-directory: './data'
        run: |
          npm install ajv
          node validate_metadata_schema.js
      - name: check for linked documentation files
        working-directory: './data'
        run: node validate_metadata_docu_files.js